### ISSUE TITLE
set up Kanban board

### ISSUE THREAD

**Issue by Kalunge** [Kalunge/javascriptcapstone#21]
[GitHub project link](https://github.com/Kalunge/javascriptcapstone/projects/1)
We are a team of two.

**Comment by henatan99** [comment]
Hi @Kalunge & @blakbox23 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- [ ]  There should be a circle with the user's avatar on each card. Kindly see the attached screenshot. 
![image](https://user-images.githubusercontent.com/64894927/132238585-cc96974e-94a2-4f73-9877-55c41264cf3c.png)

- [ ] To make it easier to trace if tasks are assigned fairly please do not remove the suffixes in the tasks ('Student A', 'StudentB'). 
![image](https://user-images.githubusercontent.com/64894927/132238842-35d307a1-2204-4b8c-b217-c9964b12323a.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by henatan99** [comment]
Hi @Kalunge && @blakbox23 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kalunge** [comment]
task asssignment done
